server:
  port: 8090
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/kayroc
    url: jdbc:mysql://mysqldb:3306/productdb
    username: root
    #password: password
    password: root
    platform: mysql
    initialization-mode: always
  application:
    name: PRODUCT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost





